<?xml version="1.0" encoding="utf-8"?>
<AddOnRegData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" SlientInstallation="No" SlientUpgrade="No" Partnernmsp="DYNAMIQ ENTERPRISE SOLUTIONS INC." SchemaVersion="3.0" Type="" MultipleVersion="false" OnDemand="" OnPremise="" ExtName="Approval Addon" ExtVersion="1.2.5" Contdata="" Partner="DYNAMIQ ENTERPRISE SOLUTIONS INC." DBType="MSSQL" ClientType="A">
  <Validity>
    <SBOCompatibility>
      <Version From="" To="" />
    </SBOCompatibility>
  </Validity>
  <Configuration>
    <Repository>
      <Properties />
    </Repository>
    <Deployment>
      <Properties />
    </Deployment>
    <Assignment>
      <Properties />
    </Assignment>
  </Configuration>
  <Addons>
    <Addon Name="" Group="" ForceFlag="" Visible="" AutoAssign="" SelfUpgrd="">
      <x86 AddonExe="" AddonSig="">
        <Installation>
          <Files />
        </Installation>
        <Uninstallation>
          <Files />
        </Uninstallation>
      </x86>
      <x64 AddonExe="C:\JOBS\VB PROJECTS\pamana_approval_addon\Approval_addon\pamana_approval_addon\bin\x64\Debug\pamana_approval_addon.exe" AddonSig="">
        <Installation>
          <Files>
            <File FileName="BouncyCastle.Cryptography.dll">
              <Actions />
            </File>
            <File FileName="BouncyCastle.Cryptography.xml">
              <Actions />
            </File>
            <File FileName="CrystalDecisions.CrystalReports.Engine.dll">
              <Actions />
            </File>
            <File FileName="CrystalDecisions.Shared.dll">
              <Actions />
            </File>
            <File FileName="MailKit.dll">
              <Actions />
            </File>
            <File FileName="MailKit.dll.config">
              <Actions />
            </File>
            <File FileName="MailKit.pdb">
              <Actions />
            </File>
            <File FileName="MailKit.xml">
              <Actions />
            </File>
            <File FileName="MimeKit.dll">
              <Actions />
            </File>
            <File FileName="MimeKit.pdb">
              <Actions />
            </File>
            <File FileName="MimeKit.xml">
              <Actions />
            </File>
            <File FileName="pamana_approval_addon.b1s">
              <Actions />
            </File>
            <File FileName="pamana_approval_addon.exe">
              <Actions />
            </File>
            <File FileName="pamana_approval_addon.exe.config">
              <Actions />
            </File>
            <File FileName="pamana_approval_addon.pdb">
              <Actions />
            </File>
            <File FileName="rpt1">
              <Actions />
            </File>
            <File FileName="SAPBusinessOneSDK.dll">
              <Actions />
            </File>
            <File FileName="stdole.dll">
              <Actions />
            </File>
            <File FileName="System.Buffers.dll">
              <Actions />
            </File>
            <File FileName="System.Buffers.xml">
              <Actions />
            </File>
            <File FileName="System.Formats.Asn1.dll">
              <Actions />
            </File>
            <File FileName="System.Formats.Asn1.xml">
              <Actions />
            </File>
            <File FileName="System.Memory.dll">
              <Actions />
            </File>
            <File FileName="System.Memory.xml">
              <Actions />
            </File>
            <File FileName="System.Numerics.Vectors.dll">
              <Actions />
            </File>
            <File FileName="System.Numerics.Vectors.xml">
              <Actions />
            </File>
            <File FileName="System.Runtime.CompilerServices.Unsafe.dll">
              <Actions />
            </File>
            <File FileName="System.Runtime.CompilerServices.Unsafe.xml">
              <Actions />
            </File>
            <File FileName="System.Threading.Tasks.Extensions.dll">
              <Actions />
            </File>
            <File FileName="System.Threading.Tasks.Extensions.xml">
              <Actions />
            </File>
            <File FileName="System.ValueTuple.dll">
              <Actions />
            </File>
            <File FileName="System.ValueTuple.xml">
              <Actions />
            </File>
            <File FileName="REPORT\PR.rpt">
              <Actions />
            </File>
          </Files>
        </Installation>
        <Uninstallation>
          <Files>
            <File FileName="BouncyCastle.Cryptography.dll">
              <Actions />
            </File>
            <File FileName="BouncyCastle.Cryptography.xml">
              <Actions />
            </File>
            <File FileName="CrystalDecisions.CrystalReports.Engine.dll">
              <Actions />
            </File>
            <File FileName="CrystalDecisions.Shared.dll">
              <Actions />
            </File>
            <File FileName="MailKit.dll">
              <Actions />
            </File>
            <File FileName="MailKit.dll.config">
              <Actions />
            </File>
            <File FileName="MailKit.pdb">
              <Actions />
            </File>
            <File FileName="MailKit.xml">
              <Actions />
            </File>
            <File FileName="MimeKit.dll">
              <Actions />
            </File>
            <File FileName="MimeKit.pdb">
              <Actions />
            </File>
            <File FileName="MimeKit.xml">
              <Actions />
            </File>
            <File FileName="pamana_approval_addon.b1s">
              <Actions />
            </File>
            <File FileName="pamana_approval_addon.exe">
              <Actions />
            </File>
            <File FileName="pamana_approval_addon.exe.config">
              <Actions />
            </File>
            <File FileName="pamana_approval_addon.pdb">
              <Actions />
            </File>
            <File FileName="rpt1">
              <Actions />
            </File>
            <File FileName="SAPBusinessOneSDK.dll">
              <Actions />
            </File>
            <File FileName="stdole.dll">
              <Actions />
            </File>
            <File FileName="System.Buffers.dll">
              <Actions />
            </File>
            <File FileName="System.Buffers.xml">
              <Actions />
            </File>
            <File FileName="System.Formats.Asn1.dll">
              <Actions />
            </File>
            <File FileName="System.Formats.Asn1.xml">
              <Actions />
            </File>
            <File FileName="System.Memory.dll">
              <Actions />
            </File>
            <File FileName="System.Memory.xml">
              <Actions />
            </File>
            <File FileName="System.Numerics.Vectors.dll">
              <Actions />
            </File>
            <File FileName="System.Numerics.Vectors.xml">
              <Actions />
            </File>
            <File FileName="System.Runtime.CompilerServices.Unsafe.dll">
              <Actions />
            </File>
            <File FileName="System.Runtime.CompilerServices.Unsafe.xml">
              <Actions />
            </File>
            <File FileName="System.Threading.Tasks.Extensions.dll">
              <Actions />
            </File>
            <File FileName="System.Threading.Tasks.Extensions.xml">
              <Actions />
            </File>
            <File FileName="System.ValueTuple.dll">
              <Actions />
            </File>
            <File FileName="System.ValueTuple.xml">
              <Actions />
            </File>
            <File FileName="REPORT\PR.rpt">
              <Actions />
            </File>
          </Files>
        </Uninstallation>
      </x64>
    </Addon>
  </Addons>
  <XApps>
    <XApp Name="" Path="" FileName="" />
  </XApps>
  <UDQs>
    <UDQ udqname="">
      <Hana FileName="" />
    </UDQ>
  </UDQs>
</AddOnRegData>